services:
  - type: web
    name: mern-task-manager
    env: node
    plan: free
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend
    startCommand: npm start --prefix backend
    publish: frontend
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://VCC:1234@cluster.3ivou.mongodb.net/?retryWrites=true&w=majority&appName=Cluster
      - key: NODE_ENV
        value: production
